$('.owl-carousel').owlCarousel({
    items:4,
    loop:false,
    center:false,
    URLhashListener:true,
    autoplayHoverPause:true,
    startPosition: 'URLHash',
    responsive:{
        0:{
            items:1,
            nav:true,
        },
        600:{
            items:2,
            nav:true
        },
        1000:{
            items:4,
            nav:true,
        }
    }
});